#!/usr/bin/env python3
# -*- coding: utf-8 -*-


import os, sys, subprocess
import time
from colorama import Fore, Back, Style, init
from simple_colors import *
import gettext


translations = gettext.translation("youtube", localedir="locales", languages=["it"])
translations.install()
_ = translations.gettext  # Definisci '_' qui

init(autoreset=True)

subprocess.call("clear", shell=True)

sys.stdout.write("\x1b[8;{rows};{cols}t".format(rows=40, cols=80))

checkfile = os.path.exists("path")
if checkfile is True:
	os.system("rm path")

#check_file = os.path.exists("/etc/sudoers")
id1 = os.system ("grep -wom1 'sudo' $HOME/.bash_history > id")
file = open("id", "r")
root1 = file.read(4 - 0)

if os.stat("id").st_size == 0:
	id2 = os.system ("grep -wom1 'su' $HOME/.bash_history > id")
	file = open("id", "r")
	root2 = file.read(4 - 0)


subprocess.call("clear", shell=True)

print()
print((Fore.RED + "  @@@@@@ @@@  @@@ @@@ @@@@@@@ @@@@@@@@       @@@@@@  @@@  @@@ "))
print((Fore.RED + " !@@     @@!  @@@ @@!   @@!   @@!           @@!  @@@ @@!  @@@ "))
print((Fore.RED + "  !@@!!  @!@  !@! !!@   @!!   @!!!:!        @!@!@!@! @!@  !@! "))
print((Fore.RED + "     !:! !!:  !!! !!:   !!:   !!:           !!:  !!!  !: .:!  "))
print((Fore.RED + " ::.: :   :.:: :  :      :    : :: :::       :   : :    ::    "))
print((Fore.RESET))
print((Fore.GREEN + "                  suiteAV-3.0 Coded by Alexis               "))
print((Fore.GREEN + "                  ---------------------------               "))
print((Fore.RESET))
print()
print()
print()
print(_("*********************************"))
print(_("*     Installation packages     *"))
print(_("*********************************"))
print()
print()
print()
print(_("[1] Start installation"))
print()
print()
print()
print()
print(_("[0] Back"))
print()
print()
print()
print()

try:
	select = eval(input(": "))
	if select >= 2:
		print()
		print(_("Option not found!"))
		input(_("Press ENTER to continue"))
		os.system("init/./packages")
except NameError:
	print()
	print(_("Invalid command!"))
	input(_("Press ENTER to continue"))
	os.system("init/./packages")
except SyntaxError:
	print()
	print(_("Invalid command!"))
	input(_("Press ENTER to continue"))
	os.system("init/./packages")
except UnboundLocalError:
	print(_("Sistema terminato"))

if select == 0:
	subprocess.call("clear", shell=True)
	subprocess.call("./suiteAV", shell=True)
	#return


def main():
	if select == 1:
		time.sleep(1)
		print()
		print(_("Installation of libraries in progress..."))
		print()
		time.sleep(2)
		if root1 == "sudo":
			print()
			print()
			print(_("Recognized maximum privilege system: %s") % (Fore.GREEN + Style.BRIGHT + root1))
			print()
			print()
			time.sleep(2)
			subprocess.call("sudo apt-get install --no-install-recommends ffmpeg libnotify-bin notification-daemon exo-utils xdg-utils", shell=True)
			subprocess.call("sudo wget -O /usr/local/bin/yt-dlp https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp  && sudo chmod a+rx /usr/local/bin/yt-dlp && sudo chmod 777 /usr/local/bin/yt-dlp", shell=True)
			subprocess.call("sudo ./patch", shell=True)
			subprocess.call("rm id", shell=True)
			time.sleep(2)
			print()
			input(_("Installation complete, press ENTER to continue!"))
			time.sleep(1)
			subprocess.call("./suiteAV", shell=True)
		else:
			print()
			print()
			print(_("Recognized maximum privilege system:", (Fore.GREEN + Style.BRIGHT + root2)))
			print()
			print()
			time.sleep(2)
			subprocess.call("su root -c 'apt-get update'", shell=True)
			subprocess.call("su root -c 'apt-get install --no-install-recommends ffmpeg libnotify-bin notification-daemon exo-utils xdg-utils'", shell=True)
			subprocess.call("su root -c 'wget -O /usr/local/bin/yt-dlp https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp && chmod a+rx /usr/local/bin/yt-dlp && chmod 777 /usr/local/bin/yt-dlp'", shell=True)
			subprocess.call("su root -c './patch'", shell=True)
			subprocess.call("rm id", shell=True)
			time.sleep(2)
			print()
			input(_("Installation complete, press ENTER to continue!"))
			time.sleep(1)
			subprocess.call("./suiteAV", shell=True)
main()
