#!/bin/bash

# Path
path=$(pwd)

# Create Link
cp $path/icons/suiteAV.png /usr/share/icons
touch /usr/share/applications/suiteav.desktop

cat << EOF >> /usr/share/applications/suiteav.desktop
[Desktop Entry]
Encoding=UTF-8
Name=suiteAV
GenericName[it]=Convertitore YouTube di Audio e Video
GenericName[it]=YouTube Converter of Audio and Video
Comment[it]=Convertitore YouTube di Audio e Video
Comment[en]=YouTube Converter of Audio and Video
Exec=x-terminal-emulator --working-directory=$path -e "bash -c 'cd $path && ./suiteAV;$SHELL'"
Terminal=false
Icon=/usr/share/icons/suiteAV.png
Type=Application
Categories=AudioVideo;
Version=1.0
EOF

# Various Settings
cd /usr/share/icons/
chmod 644 suiteAV.png
echo
sleep 2
echo "Installazione Patch completata!"
sleep 2
echo