#!/usr/bin/env python
# -*- coding: utf-8 -*-
# Version Python 2.7.*

import os, sys, subprocess
import os.path
from lib import Fore, Back, Style, init
import urllib
import signal
import time
import shlex

init(autoreset=True)

checkfile = os.path.exists("/usr/bin/xdotool")

if checkfile is True:
    id_cmd='xdotool getactivewindow'
    resize_cmd='xdotool windowsize --usehints {id} 100 40'
    proc=subprocess.Popen(shlex.split(id_cmd),stdout=subprocess.PIPE)
    windowid,err=proc.communicate()
    proc=subprocess.Popen(shlex.split(resize_cmd.format(id=windowid)))
    proc.communicate()


os.system("clear")
subprocess.call("clear", shell=True)

subprocess.call("nohup curl -O https://raw.githubusercontent.com/alexis-82/tmp/main/check 2>/dev/null", shell=True)
subprocess.call("rm nohup.out", shell=True)
check = os.path.exists("check")

subprocess.call("nohup curl -O https://ytdl-org.github.io/youtube-dl/update/versions.json 2>/dev/null", shell=True)
subprocess.call("rm nohup.out", shell=True)
subprocess.call("cat versions.json | grep latest > v1 2>/dev/null && cat v1 | sed -i 's/ //g' > v2 2>/dev/null && sed -i 's/,//g' v2", shell=True)
subprocess.call("rm versions.json", shell=True)

youtube_update = open("v2", "r")

print
print (Fore.RED + "  @@@@@@ @@@  @@@ @@@ @@@@@@@ @@@@@@@@       @@@@@@  @@@  @@@ ")
print (Fore.RED + " !@@     @@!  @@@ @@!   @@!   @@!           @@!  @@@ @@!  @@@ ")
print (Fore.RED + "  !@@!!  @!@  !@! !!@   @!!   @!!!:!        @!@!@!@! @!@  !@! ")
print (Fore.RED + "     !:! !!:  !!! !!:   !!:   !!:           !!:  !!!  !: .:!  ")
print (Fore.RED + " ::.: :   :.:: :  :      :    : :: :::       :   : :    ::    ")
print
print (Fore.GREEN + "                  suiteAV-1.8 Coded by Alexis               ")
print (Fore.GREEN + "                  ---------------------------               ")
print
print

def checkyoutube():
        checkc = open("yt-ver", "r")
        if checkc.read() == youtube_update.read():
                print "STATUS YOUTUBE-DL:",(Fore.BLACK + Back.GREEN + " NESSUN AGGIORNAMENTO ")
                print (Style.RESET_ALL)
                subprocess.call("rm v1 && rm v2", shell=True)
        else:
                print "STATUS YOUTUBE-DL:",(Fore.BLACK + Back.RED + " AGGIORNARE/UPDATE ")
                print (Style.RESET_ALL)
                subprocess.call("rm v1 && rm v2", shell=True)
checkyoutube()     
        
def checksoftware():
	if check is True:
		checka = open("check","r")
		checkb = open("version","r")
		#checkc = open("versions.json", "r")
	if check is False:
		print "STATUS SUITEAV:",(Fore.BLACK + Back.CYAN + " SITO OFFLINE ")
		print (Style.RESET_ALL)
		#subprocess.call("rm check*", shell=True)
	elif checka.read() == checkb.read():
		print "STATUS SUITEAV:",(Fore.BLACK + Back.GREEN + " NESSUN AGGIORNAMENTO ")
		print (Style.RESET_ALL)
		subprocess.call("rm check*", shell=True)
	else:
		print "STATUS SUITEAV:",(Fore.BLACK + Back.RED + " AGGIORNARE/UPDATE ")
		print (Style.RESET_ALL)
		subprocess.call("rm check*", shell=True)
checksoftware()

print
print
print "*********************************************"
print "*  Selezionare un numero / Select a number  *"
print "*********************************************"
print
print
print
print "[1] Italiano"
print "[2] English"
print
print "[3] Downloads"
print
print
print "[0] Esci / Quit"
print
print
print
print

try:
    select = input(": ")
    if select >= 4:
        print "Opzione non trovata!"
        raw_input("Premere un tasto per continuare")
        os.system("./suiteAV")
except NameError:
    print "Comando non valido!"
    raw_input("Premere un tasto per continuare")
    os.system("./suiteAV")
except SyntaxError:
    print
    print "Comando non valido!"
    raw_input("Premere un tasto per continuare")
    os.system("./suiteAV")
except UnboundLocalError:
    print "Sistema terminato"

def italiano():
	if select == 1:
		subprocess.call("init/lang/it/./italiano", shell=True)
italiano()

def english():
	if select == 2:
		subprocess.call("init/lang/en/./english", shell=True)
english()

def downloads():
	if select == 3:
		os.system("clear")
		subprocess.call("xdg-open Downloads/", shell=True)
		time.sleep(0.5)
		os.system("clear")
		os.system("./suiteAV")
downloads()

def close():
	if select == 0:
		subprocess.call("clear", shell=True)
		os.kill(os.getppid(), signal.SIGHUP)
		#os.system("exit")
		#return
close()
