#!/usr/bin/env python2
# -*- coding: utf-8 -*-
# Versione Python 2.7.*

# Import

import os, sys, subprocess
import time
from lib import Fore, Back, Style, init
import decimal
import string
init(autoreset=True)

subprocess.call("clear", shell=True)

# Start program

ytdl ="ytdl-patched"
string = "%(title)s.%(ext)s"
#vimeodwld = "vimeo"

print
print (Fore.RED + "  @@@@@@ @@@  @@@ @@@ @@@@@@@ @@@@@@@@       @@@@@@  @@@  @@@ ")
print (Fore.RED + " !@@     @@!  @@@ @@!   @@!   @@!           @@!  @@@ @@!  @@@ ")
print (Fore.RED + "  !@@!!  @!@  !@! !!@   @!!   @!!!:!        @!@!@!@! @!@  !@! ")
print (Fore.RED + "     !:! !!:  !!! !!:   !!:   !!:           !!:  !!!  !: .:!  ")
print (Fore.RED + " ::.: :   :.:: :  :      :    : :: :::       :   : :    ::    ")
print
print (Fore.GREEN + "                  suiteAV-2.0 Coded by Alexis               ")
print (Fore.GREEN + "                  ---------------------------               ")
print
print
print
print
print "*********************"
print "*  Menù Principale  *"
print "*********************"
print
print
print "[2] Aggiorna"
print
print
print "[1] YouTube"
#print "[2] Vimeo"
#print "[3] Twitch"
print
print
print "[0] Indietro"
print
print
print
print


try:
    select = input(": ")
    if select >= 3:
    	print
        print "Opzione non trovata!"
        raw_input("Premere un tasto per continuare")
        os.system("init/lang/it/./italiano")
except NameError:
    print
    print "Comando non valido!"
    raw_input("Premere un tasto per continuare")
    os.system("init/lang/it/./italiano")
except SyntaxError:
    print
    print "Comando non valido!"
    raw_input("Premere un tasto per continuare")
    os.system("init/lang/it/./italiano")
except UnboundLocalError:
    print "Sistema terminato"

# Code Exit 

if select == 0:
	subprocess.call("clear", shell=True)
	subprocess.call("./suiteAV", shell=True)

if select == 2:
	subprocess.call("init/lang/it/./update", shell=True)		


# Code start Youtube
subprocess.call("clear", shell=True)
if select == 1:
	print
	print (Fore.RED + "  @@@@@@ @@@  @@@ @@@ @@@@@@@ @@@@@@@@       @@@@@@  @@@  @@@ ")
	print (Fore.RED + " !@@     @@!  @@@ @@!   @@!   @@!           @@!  @@@ @@!  @@@ ")
	print (Fore.RED + "  !@@!!  @!@  !@! !!@   @!!   @!!!:!        @!@!@!@! @!@  !@! ")
	print (Fore.RED + "     !:! !!:  !!! !!:   !!:   !!:           !!:  !!!  !: .:!  ")
	print (Fore.RED + " ::.: :   :.:: :  :      :    : :: :::       :   : :    ::    ")
	print (Fore.RESET)
	print (Fore.GREEN + "                  suiteAV-2.0 Coded by Alexis                ")
	print (Fore.GREEN + "                  -----------------------------                ")
	print (Fore.RESET)
	print
	print
	print
	print "*****************"
	print "*-   YouTube   -*"
	print "*****************"
	print
	print "[1] Quale risoluzione posso scaricare?"
	print "[1.5] Scarica in modalità manuale"
	print
	print "[2] Scarica video a 360p"
	print "[3] Scarica video a 480p"
	print "[4] Scarica video a 720p"
	print "[5] Scarica video a migliore qualità"
	print "[5.5] Scarica video tramite file"
	print
	print
	print "Youtube o SoundCloud"
	print "--------------------"
	print
	print "[6] Scarica in MP3"
	print "[7] Scarica in MP3 HQ"
	print "[8] Scarica MP3 tramite file"
	print
	print
	print 
	print
	print "[0] Indietro"
	print
        try:
        	youtube = input(": ")
        	if youtube >=(9):
        		print
        		print "Opzione non trovata!"
        		raw_input("Premere un tasto per continuare")
        		os.system("init/lang/it/./italiano")
        except NameError:
        	print
        	print "Comando non valido!"
        	raw_input("Premere un tasto per continuare")
        	os.system("init/lang/it/./italiano")

        if youtube == 1:
			link = raw_input("Copiare il link del video: ")
			convert = "%s --list-formats %s"
			os.system(convert % (ytdl, link))
			print
			raw_input("Premere un tasto per continuare")
			subprocess.call("init/lang/it/./italiano", shell=True)
        if youtube == 2:
			link = raw_input("Copiare il link del video o playlist: ")
			convert = "%s -f 18 -o '%s' '%s'"
			os.system(convert % (ytdl, string, link))
			subprocess.call("mv *.mp4 Downloads/Video", shell=True)
			print
			print "Operazione completata!"
			print
			subprocess.call("notify-send 'suiteAV' 'Download completato!' -i /usr/share/icons/suiteAV.png", shell=True)
			time.sleep(3)
			print
			raw_input("Premere un tasto per continuare")
			subprocess.call("init/lang/it/./italiano", shell=True)
	if youtube == 3:
			link = raw_input("Copiare il link del video o playlist: ")
			convert = "%s -f 1.5.1 -o '%s' '%s'"
			os.system(convert % (ytdl, string, link))
			subprocess.call("mv *.mp4 Downloads/Video", shell=True)
			print
			print "Operazione completata!"
			print
			subprocess.call("notify-send 'suiteAV' 'Download completato!' -i /usr/share/icons/suiteAV.png", shell=True)
			time.sleep(3)
			print
			raw_input("Premere un tasto per continuare")
			subprocess.call("init/lang/it/./italiano", shell=True)
        if youtube == 4:
		    	link = raw_input("Copiare il link del video o playlist: ")
		    	convert = "%s -f 22 -o '%s' '%s'"
		    	os.system(convert % (ytdl, string, link))
		    	subprocess.call("mv *.mp4 Downloads/Video", shell=True)
		    	print
		    	print "Operazione completata!"
		    	print
		    	subprocess.call("notify-send 'suiteAV' 'Download completato!' -i /usr/share/icons/suiteAV.png", shell=True)
		    	time.sleep(3)
		    	print
		    	raw_input("Premere un tasto per continuare")
		    	subprocess.call("init/lang/it/./italiano", shell=True)
	if youtube == 5:
			link = raw_input("Copiare il link del video o playlist: ")
			convert = "%s -f b -o '%s' '%s'"
			os.system(convert % (ytdl, string, link))
			subprocess.call("mv *.mp4 Downloads/Video", shell=True)
			print
			print "Operazione completata!"
			print
			subprocess.call("notify-send 'suiteAV' 'Download completato!' -i /usr/share/icons/suiteAV.png", shell=True)
			time.sleep(3)
			print
			raw_input("Premere un tasto per continuare")
			subprocess.call("init/lang/it/./italiano", shell=True)
	if youtube == 6:
			link = raw_input("Copiare il link del video o playlist: ")
			convert ="%s -x --audio-format mp3 -o '%s' '%s'"
			os.system(convert % (ytdl, string, link))
			subprocess.call("mv *.mp3 Downloads/Audio", shell=True)
			print
			print "Operazione completata!"
			print
			subprocess.call("notify-send 'suiteAV' 'Download completato!' -i /usr/share/icons/suiteAV.png", shell=True)
			time.sleep(3)
			print
			raw_input("Premere un tasto per continuare")
			subprocess.call("init/lang/it/./italiano", shell=True)
	if youtube == 7:
			link = raw_input("Copiare il link del video o playlist: ")
			convert ="%s -x --audio-format mp3 --audio-quality 0 -o '%s' '%s'"
			os.system(convert % (ytdl, string, link))
			subprocess.call("mv *.mp3 Downloads/Audio", shell=True)
			print
			print "Operazione completata!"
			print
			subprocess.call("notify-send 'suiteAV' 'Download completato!' -i /usr/share/icons/suiteAV.png", shell=True)
			time.sleep(3)
			print
			raw_input("Premere un tasto per continuare")
			subprocess.call("init/lang/it/./italiano", shell=True)
	if youtube == 8:
			link = raw_input("Inserire il nome del file lista: ")
			convert ="%s -x --audio-format mp3 -o '%s' -a '%s'"
			os.system(convert % (ytdl, string, link))
			subprocess.call("mv *.mp3 Downloads/Audio", shell=True)
			print
			print "Operazione completata!"
			print
			subprocess.call("notify-send 'suiteAV' 'Download completato!' -i /usr/share/icons/suiteAV.png", shell=True)
			time.sleep(3)
			print
			raw_input("Premere un tasto per continuare")
			subprocess.call("init/lang/it/./italiano", shell=True)	
	if youtube == 5.5:
			file = raw_input("Inserire il nome del file lista: ")
			convert ="%s -f b -o '%s' -a '%s'"
			os.system(convert % (ytdl, string, file))
			subprocess.call("mv *.mp4 Downloads/Video", shell=True)
			print
			print "Operazione completata!"
			print
			subprocess.call("notify-send 'suiteAV' 'Download completato!' -i /usr/share/icons/suiteAV.png", shell=True)
			time.sleep(3)
			print
			raw_input("Premere un tasto per continuare")
			subprocess.call("init/lang/it/./italiano", shell=True)
        if youtube == 1.5:
                        link = raw_input("Copiare il link del video o playlist: ")
                        convert = "%s --list-formats %s"
                        os.system(convert % (ytdl, link))
                        time.sleep(4)
                        print
                        print
                        number = input("Inserire codice qualità: ")
                        convert = "%s -f '%s' -o '%s' '%s'"
                        os.system(convert % (ytdl, number, string, link))
                        subprocess.call("mv *.mp4 Downloads/Video", shell=True)
                        print
                        print "Operazione completata!"
                        print
                        subprocess.call("notify-send 'suiteAV' 'Download completato!' -i /usr/share/icons/suiteAV.png", shell=True)
                        time.sleep(3)
                        print
                        raw_input("Premere un tasto per continuare")
                        subprocess.call("init/lang/it/./italiano", shell=True)
        if youtube == 0:
			subprocess.call("clear", shell=True)
			subprocess.call("init/lang/it/./italiano", shell=True)
