#!/usr/bin/env python2
# -*- coding: utf-8 -*-
# Versione Python 2.7.*

# Importazione

import os, sys, subprocess
import time
from lib import Fore, Back, Style, init
import decimal
import signal

init(autoreset=True)

subprocess.call("clear", shell=True)

# Start program


print
print (Fore.RED + "  @@@@@@ @@@  @@@ @@@ @@@@@@@ @@@@@@@@       @@@@@@  @@@  @@@ ")
print (Fore.RED + " !@@     @@!  @@@ @@!   @@!   @@!           @@!  @@@ @@!  @@@ ")
print (Fore.RED + "  !@@!!  @!@  !@! !!@   @!!   @!!!:!        @!@!@!@! @!@  !@! ")
print (Fore.RED + "     !:! !!:  !!! !!:   !!:   !!:           !!:  !!!  !: .:!  ")
print (Fore.RED + " ::.: :   :.:: :  :      :    : :: :::       :   : :    ::    ")
print
print (Fore.GREEN + "                  suiteAV-1.6 Coded by Alexis               ")
print (Fore.GREEN + "                  ---------------------------               ")
print 
print

# Menù
print
print
print "*********************"
print "*  Menù Principale  *"
print "*********************"
print
print
print "[3] Installazione pacchetti (solo la prima volta)"
print
print
print "[1] Aggiorna suiteAV"
print "[2] Aggiorna youtube-dl"
print
print
print "[0] Esci"
print
print
print
print


try:
    select = input(": ")
    if select >= 4:
        print "Opzione non trovata!"
        raw_input("Premere un tasto per continuare")
        os.system("init/lang/it/./update")
except NameError:
    print "Comando non valido!"
    raw_input("Premere un tasto per continuare")
    os.system("init/lang/it/./update")
except SyntaxError:
    print
    print "Comando non valido!"
    raw_input("Premere un tasto per continuare")
    os.system("init/lang/it/./update")
except UnboundLocalError:
    print "Sistema terminato"


if select == 0:
	subprocess.call("clear", shell=True)
	subprocess.call("init/lang/it/./italiano", shell=True)
		

def pacchetti():
	if select == 3:
		subprocess.call("init/lang/it/./lib_it", shell=True)
pacchetti()

def suiteAV():
	if select == 1:		
		time.sleep(1)
		print
		print "In aggiornamento..."
		print	
		subprocess.call("cd .. && wget https://github.com/alexis-82/suiteAV/archive/master.zip && unzip master.zip && cp -rf suiteAV-master/* suiteAV && rm -rf suiteAV-master master.zip", shell=True)
		time.sleep(3)
		print
		print "Aggiornamento di suiteAV completato, riavviare il programma!"
		print
		subprocess.call("notify-send 'suiteAV' 'Aggiornamento di suiteAV completato!' -i /usr/share/icons/suiteAV.png", shell=True)
		time.sleep(3)
		print
		raw_input("Premere un tasto per continuare")
		subprocess.call("clear", shell=True)
		os.kill(os.getppid(), signal.SIGHUP)
suiteAV()

def yt_dl():
	if select == 2:
		time.sleep(1)
		print
		print "In aggiornamento..."
		print
		subprocess.call("youtube-dl -U && curl -o youtube https://raw.githubusercontent.com/rg3/youtube-dl/master/youtube_dl/version.py", shell=True)
		time.sleep(3)
		print
		print "Aggiornamento completato!"
		print
		subprocess.call("notify-send 'suiteAV' 'Aggiornamento completato!' -i /usr/share/icons/suiteAV.png", shell=True)
		time.sleep(3)
		print
		raw_input("Premere un tasto per continuare!")
		subprocess.call("./suiteAV", shell=True)
yt_dl()
