#!/usr/bin/env python2
# -*- coding: utf-8 -*-
# Versione Python 2.7.*

# Import

import os, sys, subprocess
import time
from lib import Fore, Back, Style, init
import decimal
import string
init(autoreset=True)

subprocess.call("clear", shell=True)

# Start program

ytdl ="ytdl-patched"
string = "%(title)s.%(ext)s"
#vimeodwld = "vimeo"

print
print (Fore.RED + "  @@@@@@ @@@  @@@ @@@ @@@@@@@ @@@@@@@@       @@@@@@  @@@  @@@ ")
print (Fore.RED + " !@@     @@!  @@@ @@!   @@!   @@!           @@!  @@@ @@!  @@@ ")
print (Fore.RED + "  !@@!!  @!@  !@! !!@   @!!   @!!!:!        @!@!@!@! @!@  !@! ")
print (Fore.RED + "     !:! !!:  !!! !!:   !!:   !!:           !!:  !!!  !: .:!  ")
print (Fore.RED + " ::.: :   :.:: :  :      :    : :: :::       :   : :    ::    ")
print
print (Fore.GREEN + "                  suiteAV-2.0 Coded by Alexis               ")
print (Fore.GREEN + "                  ---------------------------               ")
print
print
print
print
print "***************"
print "*  Main Menù  *"
print "***************"
print
print
print "[2] Update"
print
print
print "[1] YouTube"
#print "[2] Vimeo"
#print "[3] Twitch"
print
print
print "[0] Back"
print
print
print
print

try:
    select = input(": ")
    if select >= 3:
    	print
        print "Option not found!"
        raw_input("Press any key to continue")
        os.system("init/lang/en/./english")
except NameError:
    print
    print "Invalid command!"
    raw_input("Press any key to continue")
    os.system("init/lang/en/./english")
except SyntaxError:
    print
    print "Invalid command!"
    raw_input("Press any key to continue")
    os.system("init/lang/en/./english")
except UnboundLocalError:
    print
    print "System terminated"

# Code Exit 

if select == 0:
	subprocess.call("clear", shell=True)
	subprocess.call("./suiteAV", shell=True)

if select == 2:
	subprocess.call("init/lang/en/./update", shell=True)		


# Code start Youtube
subprocess.call("clear", shell=True)
if select == 1:
	print
	print (Fore.RED + "  @@@@@@ @@@  @@@ @@@ @@@@@@@ @@@@@@@@       @@@@@@  @@@  @@@ ")
	print (Fore.RED + " !@@     @@!  @@@ @@!   @@!   @@!           @@!  @@@ @@!  @@@ ")
	print (Fore.RED + "  !@@!!  @!@  !@! !!@   @!!   @!!!:!        @!@!@!@! @!@  !@! ")
	print (Fore.RED + "     !:! !!:  !!! !!:   !!:   !!:           !!:  !!!  !: .:!  ")
	print (Fore.RED + " ::.: :   :.:: :  :      :    : :: :::       :   : :    ::    ")
	print (Fore.RESET)
	print (Fore.GREEN + "                  suiteAV-2.0 Coded by Alexis                ")
	print (Fore.GREEN + "                  -----------------------------                ")
	print (Fore.RESET)
	print
	print
	print
	print "*****************"
	print "*-   YouTube   -*"
	print "*****************"
	print
	print "[1] What resolution can I download?"
	print "[1.5] Download in manual mode"
	print
	print "[2] Download video at 360p"
	print "[3] Download video at 480p"
	print "[4] Download video at 720p"
	print "[5] Download video at 1080p"
	print "[5.5] Video download via file"
	print
	print
	print "Youtube or SoundCloud"
	print "---------------------"
	print
	print "[6] Download in MP3"
	print "[7] Download in MP3 HQ"
	print "[8] Download MP3 via file"
	print
	print
	print 
	print
	print "[0] Back"
	print
        try:
        	youtube = input(": ")
        	if youtube >=(9):
        		print
        		print "Number not found!"
        		raw_input("Press any key to continue")
        		os.system("init/lang/en/./english")
        except NameError:
        	print
        	print "Command not found!"
        	raw_input("Press any key to continue")
        	os.system("init/lang/en/./english")

	if youtube == 1:
			link = raw_input("Copy the video link: ")
			convert = "%s --list-formats %s"
			os.system(convert % (ytdl, link))
			print
			raw_input("Press any key to continue")
			subprocess.call("init/lang/en/./english", shell=True)
	if youtube == 2:
			link = raw_input("Copy the video link or playlist: ")
			convert = "%s -f 18 -o '%s' '%s'"
			os.system(convert % (ytdl, string, link))
			subprocess.call("mv *.mp4 Downloads/Video", shell=True)
			print
			print "Operation Complete!"
			print
			subprocess.call("notify-send 'suiteAV' 'Download completed!' -i /usr/share/icons/suiteAV.png", shell=True)
			time.sleep(3)
			print
			raw_input("Press any key to continue")
			subprocess.call("init/lang/en/./english", shell=True)
	elif youtube == 3:
			link = raw_input("Copy the video link or playlist: ")
			convert = "%s -f 1.5.1 -o '%s' '%s'"
			os.system(convert % (ytdl, string, link))
			subprocess.call("mv *.mp4 Downloads/Video", shell=True)
			print
			print "Operation Complete!"
			print
			subprocess.call("notify-send 'suiteAV' 'Download completed!' -i /usr/share/icons/suiteAV.png", shell=True)
			time.sleep(3)
			print
			raw_input("Press any key to continue")
			subprocess.call("init/lang/en/./english", shell=True)
	if youtube == 4:
			link = raw_input("Copy the video link or playlist: ")
			convert = "%s -f 22 -o '%s' '%s'"
			os.system(convert % (ytdl, string, link))
			subprocess.call("mv *.mp4 Downloads/Video", shell=True)
			print
			print "Operation Complete!"
			print
			subprocess.call("notify-send 'suiteAV' 'Download completed!' -i /usr/share/icons/suiteAV.png", shell=True)
			time.sleep(3)
			print
			raw_input("Press any key to continue")
			subprocess.call("init/lang/en/./english", shell=True)
	elif youtube == 5:
			link = raw_input("Copy the video link or playlist: ")
			convert = "%s -f 137+251 -o '%s' '%s'"
			os.system(convert % (ytdl, string, link))
			subprocess.call("mv *.mkv *.mp4 Downloads/Video", shell=True)
			print
			print "Operation Complete!"
			print
			subprocess.call("notify-send 'suiteAV' 'Download completed!' -i /usr/share/icons/suiteAV.png", shell=True)
			time.sleep(3)
			print
			raw_input("Press any key to continue")
			subprocess.call("init/lang/en/./english", shell=True)
	elif youtube == 6:
			link = raw_input("Copy the video link or playlist: ")
			convert ="%s -x --audio-format mp3 -o '%s' '%s'"
			os.system(convert % (ytdl, string, link))
			subprocess.call("mv *.mp3 Downloads/Audio", shell=True)
			print
			print "Operation Complete!"
			print
			subprocess.call("notify-send 'suiteAV' 'Download completed!' -i /usr/share/icons/suiteAV.png", shell=True)
			time.sleep(3)
			print
			raw_input("Press any key to continue")
			subprocess.call("init/lang/en/./english", shell=True)
	elif youtube == 7:
			link = raw_input("Copy the video link or playlist: ")
			convert ="%s -x --audio-format mp3 --audio-quality 0 -o '%s' '%s'"
			os.system(convert % (ytdl, string, link))
			subprocess.call("mv *.mp3 Downloads/Audio", shell=True)
			print
			print "Operation Complete!"
			print
			subprocess.call("notify-send 'suiteAV' 'Download completed!' -i /usr/share/icons/suiteAV.png", shell=True)
			time.sleep(3)
			print
			raw_input("Press any key to continue")
			subprocess.call("init/lang/en/./english", shell=True)
	elif youtube == 8:
			link = raw_input("Enter the name of the list file: ")
			convert ="%s -x --audio-format mp3 -o '%s' -a '%s'"
			os.system(convert % (ytdl, string, link))
			subprocess.call("mv *.mp3 Downloads/Audio", shell=True)
			print
			print "Operation Complete!"
			print
			subprocess.call("notify-send 'suiteAV' 'Download completed!' -i /usr/share/icons/suiteAV.png", shell=True)
			time.sleep(3)
			print
			raw_input("Press any key to continue")
			subprocess.call("init/lang/en/./english", shell=True)	
	elif youtube == 5.5:
			file = raw_input("Enter the name of the list file: ")
			convert ="%s -f 137+251 -o '%s' -a '%s'"
			os.system(convert % (ytdl, string, file))
			subprocess.call("mv *.mkv *.mp4 Downloads/Video", shell=True)
			print
			print "Operation Complete!"
			print
			subprocess.call("notify-send 'suiteAV' 'Download completed!' -i /usr/share/icons/suiteAV.png", shell=True)
			time.sleep(3)
			print
			raw_input("Press any key to continue")
			subprocess.call("init/lang/en/./english", shell=True)
        if youtube == 1.5:
                        link = raw_input("Copy the video link or playlist: ")
                        convert = "%s --list-formats %s"
                        os.system(convert % (ytdl, link))
                        time.sleep(4)
                        print
                        print
                        number = raw_input("Enter quality code: ")
                        convert = "%s -f '%s' -o '%s' '%s'"
                        os.system(convert % (ytdl, number, string, link))
                        subprocess.call("mv *.mkv *.mp4 Downloads/Video", shell=True)
                        print
                        print "Operation Complete!"
                        print
                        subprocess.call("notify-send 'suiteAV' 'Download completed!' -i /usr/share/icons/suiteAV.png", shell=True)
                        time.sleep(3)
                        print
                        raw_input("Press any key to continue")
                        subprocess.call("init/lang/en/./english", shell=True)
	if youtube == 0:
			subprocess.call("clear", shell=True)
			subprocess.call("init/lang/en/./english", shell=True)
