#!/usr/bin/env python2
# -*- coding: utf-8 -*-
# Version Python 2.7.*

import os, sys, subprocess
import time
from lib import Fore, Back, Style, init
init(autoreset=True)

checkfile = os.path.exists("path")
if checkfile is True:
	os.system("rm path")

#check_file = os.path.exists("/etc/sudoers")
id1 = os.system ("grep -wom1 'sudo' $HOME/.bash_history > id")
file = open("id", "r")
root1 = file.read(4 - 0)

if os.stat("id").st_size == 0:
	id2 = os.system ("grep -wom1 'su' $HOME/.bash_history > id")
	file = open("id", "r")
	root2 = file.read(4 - 0)


subprocess.call("clear", shell=True)

print
print (Fore.RED + "  @@@@@@ @@@  @@@ @@@ @@@@@@@ @@@@@@@@       @@@@@@  @@@  @@@ ")
print (Fore.RED + " !@@     @@!  @@@ @@!   @@!   @@!           @@!  @@@ @@!  @@@ ")
print (Fore.RED + "  !@@!!  @!@  !@! !!@   @!!   @!!!:!        @!@!@!@! @!@  !@! ")
print (Fore.RED + "     !:! !!:  !!! !!:   !!:   !!:           !!:  !!!  !: .:!  ")
print (Fore.RED + " ::.: :   :.:: :  :      :    : :: :::       :   : :    ::    ")
print
print (Fore.GREEN + "                  suiteAV-1.8 Coded by Alexis               ")
print (Fore.GREEN + "                  ---------------------------               ")
print
print
print
print
print "*********************************"
print "*     Packages Installation     *"
print "*********************************"
print
print
print
print "[1] Start the procedure"
print
print
print
print "[0] Back"
print
print
print
print

try:
    select = input(": ")
    if select >= 2:
        print "Opzione non trovata!"
        raw_input("Premere un tasto per continuare")
        os.system("init/lang/en/./lib_en")
except NameError:
    print "Comando non valido!"
    raw_input("Premere un tasto per continuare")
    os.system("init/lang/en/./lib_en")
except SyntaxError:
    print
    print "Comando non valido!"
    raw_input("Premere un tasto per continuare")
    os.system("init/lang/en/./lib_en")
except UnboundLocalError:
    print "Sistema terminato"

if select == 0:
	subprocess.call("clear", shell=True)
	subprocess.call("init/lang/en/./english", shell=True)
	#return



if select is 1:
	time.sleep(1)
	print
	print "Installing libraries..."
	print
	time.sleep(2)
	if root1 == "sudo":
		print
		print
		print  "System of the highest privileges recognized:", (Fore.GREEN + Style.BRIGHT + root1)
		print
		print
		time.sleep(2)
		subprocess.call("sudo apt-get install ffmpeg libnotify-bin notification-daemon exo-utils xdotool", shell=True)
		#subprocess.call("sudo apt-get install curl", shell=True)
		subprocess.call("sudo curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl && sudo chmod a+rx /usr/local/bin/youtube-dl && sudo chmod 777 /usr/local/bin/youtube-dl", shell=True) 
		subprocess.call("sudo ./patch", shell=True)
		time.sleep(2)
		print
		raw_input("Installation complete, press a button to continue!")
		time.sleep(1)
		subprocess.call("./suiteAV", shell=True)	
	else:
		print
		print
		print  "System of the highest privileges recognized:", (Fore.GREEN + Style.BRIGHT + root2)
		print
		print
		time.sleep(2)		
		subprocess.call("su root -c 'apt-get update'", shell=True)
		subprocess.call("su root -c 'apt-get install ffmpeg libnotify-bin notification-daemon exo-utils xdotool'", shell=True)
		#subprocess.call("su root -c 'apt-get install curl'", shell=True)
		subprocess.call("su root -c 'curl -L https://yt-dl.org/latest/youtube-dl -o /usr/local/bin/youtube-dl && chmod a+x /usr/local/bin/youtube-dl' && chmod 777 /usr/local/bin/youtube-dl", shell=True) 
		subprocess.call("su root -c './patch'", shell=True)
		time.sleep(2)
		print
		raw_input("Installation complete, press a button to continue!")
		time.sleep(1)
		subprocess.call("./suiteAV", shell=True)