#!/usr/bin/env python2
# -*- coding: utf-8 -*-
# Versione Python 2.7.*

# Importazione

import os, sys, subprocess
import time
from lib import Fore, Back, Style, init
import decimal
import signal

init(autoreset=True)

subprocess.call("clear", shell=True)

# Start program


print
print (Fore.RED + "  @@@@@@ @@@  @@@ @@@ @@@@@@@ @@@@@@@@       @@@@@@  @@@  @@@ ")
print (Fore.RED + " !@@     @@!  @@@ @@!   @@!   @@!           @@!  @@@ @@!  @@@ ")
print (Fore.RED + "  !@@!!  @!@  !@! !!@   @!!   @!!!:!        @!@!@!@! @!@  !@! ")
print (Fore.RED + "     !:! !!:  !!! !!:   !!:   !!:           !!:  !!!  !: .:!  ")
print (Fore.RED + " ::.: :   :.:: :  :      :    : :: :::       :   : :    ::    ")
print
print (Fore.GREEN + "                  suiteAV-1.2 Coded by Alexis               ")
print (Fore.GREEN + "                  ---------------------------               ")
print 
print

# Menù
print
print
print "***************"
print "*  Main Menù  *"
print "***************"
print
print
print "[1] Install packages (first time only)"
print
print
print "[2] Update suiteAV"
print "[3] Update youtube-dl"
print
print
print "[0] Back"
print
print
print
print


select = input(": ")


if select == 0:
	subprocess.call("clear", shell=True)
	subprocess.call("./suiteAV", shell=True)
		

def pacchetti():
	if select == 1:
		subprocess.call("init/lang/en/./english", shell=True)
pacchetti()

def suiteAV():
	if select == 2:		
		time.sleep(1)
		print
		print "Updating..."
		print	
		subprocess.call("cd .. && git clone https://github.com/alexis-82/suiteAV.git", shell=True)
		time.sleep(3)
		print
		print "SuiteAV update completed, restart the program!"
		print
		subprocess.call("notify-send 'suiteAV-1.0' 'SuiteAV update completed!' -i /usr/share/icons/suiteAV.png", shell=True)
		time.sleep(3)
		print
		raw_input("Press any key to continue")
		subprocess.call("clear", shell=True)
		os.kill(os.getppid(), signal.SIGHUP)
suiteAV()

def yt_dl():
	if select == 3:
		time.sleep(1)
		print
		print "Updating..."
		print
		subprocess.call("youtube-dl -U && curl -o youtube https://raw.githubusercontent.com/rg3/youtube-dl/master/youtube_dl/version.py", shell=True)
		time.sleep(3)
		print
		print "Update Completed!"
		print
		subprocess.call("notify-send 'suiteAV' 'Update Completed!' -i /usr/share/icons/suiteAV.png", shell=True)
		time.sleep(3)
		print
		raw_input("Press any key to continue!")
		subprocess.call("./suiteAV", shell=True)
yt_dl()