#!/usr/bin/env python2
# -*- coding: utf-8 -*-
# Versione Python 2.7.*

# Importazione

import os, sys, subprocess
import time
from lib import Fore, Back, Style, init
import decimal
import signal

init(autoreset=True)

subprocess.call("clear", shell=True)

id1 = os.system ("grep -wom1 'sudo' $HOME/.bash_history > id")
file = open("id", "r")
root1 = file.read(4 - 0)

if os.stat("id").st_size == 0:
	id2 = os.system ("grep -wom1 'su' $HOME/.bash_history > id")
	file = open("id", "r")
	root2 = file.read(4 - 0)

# Start program


print
print (Fore.RED + "  @@@@@@ @@@  @@@ @@@ @@@@@@@ @@@@@@@@       @@@@@@  @@@  @@@ ")
print (Fore.RED + " !@@     @@!  @@@ @@!   @@!   @@!           @@!  @@@ @@!  @@@ ")
print (Fore.RED + "  !@@!!  @!@  !@! !!@   @!!   @!!!:!        @!@!@!@! @!@  !@! ")
print (Fore.RED + "     !:! !!:  !!! !!:   !!:   !!:           !!:  !!!  !: .:!  ")
print (Fore.RED + " ::.: :   :.:: :  :      :    : :: :::       :   : :    ::    ")
print
print (Fore.GREEN + "                  suiteAV-2.0 Coded by Alexis               ")
print (Fore.GREEN + "                  ---------------------------               ")
print 
print

print
print
print "***************"
print "*  Main Menù  *"
print "***************"
print
print
print "[3] Install packages (first time only)"
print
print
print "[1] Update suiteAV"
print "[2] Update youtube-dl"
print
print
print "[0] Back"
print
print
print
print


try:
    select = input(": ")
    if select >= 4:
        print "Opzione non trovata!"
        raw_input("Premere un tasto per continuare")
        os.system("init/lang/en/./update")
except NameError:
    print "Comando non valido!"
    raw_input("Premere un tasto per continuare")
    os.system("init/lang/en/./update")
except SyntaxError:
    print
    print "Comando non valido!"
    raw_input("Premere un tasto per continuare")
    os.system("init/lang/en/./update")
except UnboundLocalError:
    print "Sistema terminato"



if select == 0:
	subprocess.call("clear", shell=True)
	subprocess.call("init/lang/en/./english", shell=True)
		

def pacchetti():
	if select == 3:
		subprocess.call("init/lang/en/./lib_en", shell=True)
pacchetti()

def suiteAV():
	if select == 1:		
		time.sleep(1)
		print
		print "Updating..."
		print	
		subprocess.call("cd .. && wget https://github.com/alexis-82/suiteAV/archive/master.zip && unzip master.zip && cp -rf suiteAV-master/* suiteAV && rm -rf suiteAV-master master.zip", shell=True)
		time.sleep(3)
		print
		print "SuiteAV update completed, restart the program!"
		print
		subprocess.call("notify-send 'suiteAV-1.0' 'SuiteAV update completed!' -i /usr/share/icons/suiteAV.png", shell=True)
		time.sleep(3)
		print
		raw_input("Press any key to continue")
		subprocess.call("clear", shell=True)
		os.kill(os.getppid(), signal.SIGHUP)
suiteAV()

def yt_dl():
	if select == 2:
		time.sleep(1)
		print
		print "In aggiornamento..."
		print
		if root1 == "sudo":
			subprocess.call("sudo ytdl-patched -U", shell=True)
			subprocess.call("ytdl-patched -V > yt-ver", shell=True)
			subprocess.call("rm id", shell=True)
			time.sleep(3)
			print
			print "Update Completed!"
			print
			subprocess.call("notify-send 'suiteAV' 'Update Completed!' -i /usr/share/icons/suiteAV.png", shell=True)
			time.sleep(3)
			print
			raw_input("Press any key to continue!")
			subprocess.call("./suiteAV", shell=True)
		else:
			subprocess.call("su root -c 'ytdl-patched -U'", shell=True)
			subprocess.call("ytdl-patched -V > yt-ver", shell=True)
			subprocess.call("rm id", shell=True)
			time.sleep(3)
			print
			print "Update Completed!"
			print
			subprocess.call("notify-send 'suiteAV' 'Update Completed!' -i /usr/share/icons/suiteAV.png", shell=True)
			time.sleep(3)
			print
			raw_input("Press any key to continue!")
			subprocess.call("./suiteAV", shell=True)

yt_dl()